# Meltano Configuration File
#
# Sample usage:
# > meltano run tap-daap-payroll target-duckdb
#
# Or equivalently:
# > meltano run el  # Run the job named 'el' to extract and load data

version: 1
project_id: DAAP Payroll Project

env:
  DAAP_DB_PATH: ./reports/daap_payroll.duckdb
  DAAP_DB_NAME: daap_payroll
  DAAP_RAW_SCHEMA: payroll_raw
  EMPLOYEE_RAW_SCHEMA: payroll_raw
  CPPS_ACTIVE_RAW_SCHEMA: payroll_raw

default_environment: dev
environments:
  - name: dev

plugins:
  extractors:
    - name: tap-csv
      namespace: tap_daap_payroll
      variant: meltanolabs
      pip_url: git+https://github.com/MeltanoLabs/tap-csv.git@v1.0.1
      capabilities:
        - catalog
        - discover
      config:
        files:
          - entity: dummydata
            path: daap-sample-data/dummydata.csv
            keys:
            - EMP_ID
            delimiter: ","
          - entity: steps_sample_data
            path: daap-sample-data/steps_sample_data.csv
            keys:
            - emp_id
            delimiter: ","
          - entity: cpps_active_employees
            path: daap-sample-data/cpps_active_employees.csv
            keys:
            - emp_id
            delimiter: ","
  loaders:
    - name: target-duckdb
      variant: jwills
      pip_url: target-duckdb~=0.4
      config:
        filepath: ${DAAP_DB_PATH}
        default_target_schema: $DAAP_RAW_SCHEMA

jobs:
  # Sample usage:  `meltano run el`
  # Equivalent to: `meltano run tap-daap-payroll target-duckdb`
  - name: el # Extract and load the raw data
    tasks:
      - tap-csv target-duckdb


