duckdb:
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DAAP_DB_PATH', './reports/daap_payroll.duckdb') }}"
      database: "{{ env_var('DAAP_DB_NAME', 'daap_payroll') }}"
      schema: "{{ env_var('DAAP_TARGET_SCHEMA', 'analytics') }}"
      threads: 4
  target: dev
